import { useState } from 'react';

function ProgressRing({ value }) {
  return <div className="relative flex h-24 w-24 shrink-0 items-center justify-center rounded-full" style={{ background: `conic-gradient(#6366f1 ${value * 3.6}deg, #e8ebf2 0deg)` }}><div className="flex h-16 w-16 items-center justify-center rounded-full bg-white text-lg font-bold text-slate-900">{value}%</div></div>;
}

function StatusSelect({ item, onChange }) {
  const tone = item.status === 'Completed' ? 'status-complete' : item.status === 'Currently Learning' ? 'status-learning' : 'status-idle';
  return <select value={item.status} onChange={(event) => onChange(event.target.value)} className={`status-pill ${tone}`} aria-label={`Status for ${item.title}`}><option value="Not Started">Not started</option><option value="Currently Learning">In progress</option><option value="Completed">Completed</option></select>;
}

function Check({ checked, onChange, label }) {
  return <label className="check-control" title={label}><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span aria-hidden="true">{checked ? '✓' : ''}</span></label>;
}

export function DashboardShell({ session, data, stats, learningProgress, filter, search, setFilter, setSearch, filteredCategories, filteredProjects, update, setModal, onProfile, onSignOut, itemType, setItemType, newTitle, setNewTitle, categoryId, setCategoryId, addItem, reset, modal }) {
  const [section, setSection] = useState('overview');
  const metadata = session.user.user_metadata || {};
  const displayName = metadata.full_name || metadata.name || session.user.email?.split('@')[0] || 'Learner';
  const avatar = metadata.avatar_url || metadata.picture;
  const topics = data.categories.flatMap((category) => category.topics);
  const activeTopics = topics.filter((topic) => topic.status !== 'Completed');
  const continueTopic = activeTopics[0] || topics[0];
  const topicProgress = (topic) => learningProgress[topic.id]?.exam_complete ? 100 : learningProgress[topic.id]?.exercise_complete ? 66 : learningProgress[topic.id]?.lesson_complete ? 33 : 0;
  const visibleCategories = section === 'projects' ? [] : filteredCategories;
  const showProjects = section === 'projects' || section === 'overview';
  const nav = [['overview', 'Overview'], ['roadmap', 'Roadmap'], ['projects', 'Projects'], ['learning', 'Learning']];

  return <div className="workspace-shell"><aside className="workspace-sidebar"><div className="brand-lockup"><div className="brand-mark">R</div><div><strong>Roadmap</strong><span>Learning workspace</span></div></div><nav className="workspace-nav" aria-label="Main navigation">{nav.map(([id, label]) => <button key={id} onClick={() => setSection(id)} className={section === id ? 'nav-item active' : 'nav-item'}><span className="nav-dot" />{label}</button>)}</nav><div className="sidebar-note"><span className="eyebrow">Your momentum</span><strong>{stats.progress}% complete</strong><div className="mini-progress"><span style={{ width: `${stats.progress}%` }} /></div><p>Small steps compound into real skills.</p></div><div className="sidebar-footer"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></aside>
    <div className="workspace-main"><header className="workspace-header"><div className="mobile-brand"><div className="brand-mark">R</div><strong>Roadmap</strong></div><div className="header-search"><span aria-hidden="true">⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search your roadmap..." aria-label="Search roadmap" /></div><div className="header-actions"><button onClick={() => setModal('add')} className="primary-action">+ Add item</button><button onClick={onProfile} className="profile-trigger" aria-label="Open profile"><span className="avatar">{avatar ? <img src={avatar} alt="" /> : displayName[0].toUpperCase()}</span><span className="profile-name">{displayName}</span><span aria-hidden="true">⌄</span></button><button onClick={onSignOut} className="signout-action">Log out</button></div></header><main className="workspace-content"><div className="page-heading"><div><p className="eyebrow">{section === 'learning' ? 'Study plan' : 'Personal dashboard'}</p><h1>{section === 'projects' ? 'Project studio' : section === 'roadmap' ? 'Your roadmap' : section === 'learning' ? 'Learning center' : `Good to see you, ${displayName.split(' ')[0]}`}</h1><p className="page-subtitle">{section === 'overview' ? 'Keep your next milestone in sight and make steady progress.' : 'A focused space for building practical skills at your pace.'}</p></div><div className="header-date">Updated today <span className="live-dot" /></div></div>

      {section === 'overview' && <section className="hero-card"><div><span className="hero-kicker">NEXT UP</span><h2>{continueTopic ? continueTopic.title : 'Your roadmap is ready'}</h2><p>Continue your learning path with a focused lesson, exercise, and exam.</p>{continueTopic && <button onClick={() => setModal(`learning:${continueTopic.id}`)} className="hero-button">Continue learning <span>→</span></button>}</div><ProgressRing value={stats.learningProgress} /></section>}

      <section className="metric-grid"><article className="metric-card"><span className="metric-icon indigo">◎</span><div><span className="metric-label">Roadmap items</span><strong>{stats.total}</strong><small>{stats.completed} completed</small></div></article><article className="metric-card"><span className="metric-icon cyan">↗</span><div><span className="metric-label">In progress</span><strong>{stats.learning}</strong><small>Keep the momentum</small></div></article><article className="metric-card"><span className="metric-icon emerald">✓</span><div><span className="metric-label">Learning progress</span><strong>{stats.learningProgress}%</strong><small>Lessons and exams</small></div></article></section>

      <section className="toolbar"><div><h2>{section === 'projects' ? 'Projects' : section === 'learning' ? 'Lessons to explore' : 'Roadmap topics'}</h2><p>{section === 'overview' ? 'Organized by skill area' : 'Choose an item to open its learning path'}</p></div><div className="toolbar-controls"><select value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter roadmap"><option value="all">All statuses</option><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="completed">Completed</option></select><button onClick={() => setModal('add')} className="icon-action" title="Add custom item">+</button></div></section>

      {section !== 'projects' && <section className="category-grid">{visibleCategories.map((category) => <article className="category-panel" key={category.id}><div className="category-title"><div><h3>{category.name}</h3><span>{category.topics.length} learning units</span></div><span className="category-arrow">↗</span></div><div className="topic-stack">{category.topics.map((topic) => <div className="topic-row" key={topic.id}><button onClick={() => setModal(`learning:${topic.id}`)} className="topic-link"><Check checked={topic.status === 'Completed'} label={`Mark ${topic.title} complete`} onChange={(checked) => update(topic.id, checked ? 'Completed' : 'Not Started')} /><span><strong>{topic.title}</strong><small>{topicProgress(topic)}% learning path</small></span></button><StatusSelect item={topic} onChange={(status) => update(topic.id, status)} /></div>)}</div></article>)}</section>}

      {showProjects && <><section className="toolbar projects-heading"><div><h2>Build projects</h2><p>Turn concepts into something real.</p></div></section><section className="project-grid">{filteredProjects.map((project) => <article className="project-card" key={project.id}><div className="project-card-top"><span className="project-symbol">↗</span><StatusSelect item={project} onChange={(status) => update(project.id, status, status === 'Completed' ? new Date().toISOString().slice(0, 10) : null)} /></div><h3>{project.title}</h3><div className="project-card-bottom"><Check checked={project.status === 'Completed'} label={`Mark ${project.title} complete`} onChange={(checked) => update(project.id, checked ? 'Completed' : 'Not Started', checked ? new Date().toISOString().slice(0, 10) : null)} /><span>{project.status === 'Completed' ? 'Completed' : 'Ready to build'}</span></div></article>)}</section></>}
    </main>{modal === 'add' && <div className="workspace-modal" onMouseDown={(event) => event.target === event.currentTarget && setModal(null)}><section className="workspace-dialog"><div className="dialog-heading"><div><span className="eyebrow">New item</span><h2>Add to your roadmap</h2></div><button onClick={() => setModal(null)} className="dialog-close" aria-label="Close">×</button></div><form onSubmit={addItem} className="dialog-form"><label>Type<select value={itemType} onChange={(event) => setItemType(event.target.value)}><option value="topic">Roadmap topic</option><option value="project">Project</option></select></label>{itemType === 'topic' && <label>Category<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}>{data.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>}<label>Title<input required value={newTitle} onChange={(event) => setNewTitle(event.target.value)} placeholder="e.g. Accessibility basics" /></label><button className="primary-action dialog-submit">Add item</button></form></section></div>}{modal === 'reset' && <div className="workspace-modal"><section className="workspace-dialog"><span className="eyebrow">Start fresh</span><h2>Reset your roadmap?</h2><p className="dialog-copy">Your current items will be removed and the starter roadmap will be restored.</p><div className="dialog-actions"><button onClick={() => setModal(null)} className="secondary-action">Cancel</button><button onClick={reset} className="danger-action">Reset roadmap</button></div></section></div>}</div></div>;
}
